language: python
sudo: false

python:
    - 2.7
    - 3.4

branches:
    only:
        - master
        - develop

install:
    - pip install codecov
    - pip install pytest-cov
    - pip install pytest-pep8

script:
    - py.test --cov .

after_success:
    - codecov
